# Generated by Django 4.2 on 2025-04-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passports/', verbose_name='Passpost/metrka'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday: 0000-00-00'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Kurs *'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ismi familiya *'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, default=998, null=True, verbose_name='Telefon *'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_time',
            field=models.CharField(blank=True, choices=[('8:00 - 10:00', '8:00 - 10:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('12:00 - 14:00', '12:00 - 14:00'), ('14:00 - 16:00', '14:00 - 16:00'), ('16:00 - 18:00', '16:00 - 18:00')], max_length=200, null=True, verbose_name='Vaqt *'),
        ),
    ]
