# Generated by Django 4.2 on 2025-01-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='energy',
            new_name='summa',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='others',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='rent',
        ),
        migrations.AddField(
            model_name='expenses',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sababi'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='month',
            field=models.DateField(blank=True, null=True, verbose_name='Qaysi oy: 2025-01-01'),
        ),
    ]
